10:25:03:  = Creation of this file = 

10:25:03: Date 15/10/2021 already added (date ID: 18)
10:25:03: HTTPConnectionPool(host='firefox_webdriver', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d1d4b68f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
10:25:03: The connection to remote webdriver failed. Check if the container is running.
10:25:03: If it is, check the hostname in globals.py and other connection settings.

